name: bor_nov_site
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.10.8

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  audioplayers: ^6.5.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  go_router: ^17.1.0

flutter:
  uses-material-design: true

  assets:
    - assets/pictures/09_02-14_02/title_1.png
    - assets/pictures/09_02-14_02/page_1.png
    - assets/pictures/09_02-14_02/page_2.png
    - assets/pictures/09_02-14_02/page_3.png
    - assets/pictures/09_02-14_02/page_4.png
    - assets/pictures/09_02-14_02/last_1.png
    - assets/pictures/bg/backg.png
    - assets/pictures/15_02-21_02/15.02-21.02.png
    - assets/pictures/15_02-21_02/Газета 15-21 лют стор. 1.png
    - assets/pictures/15_02-21_02/Газета 15-21 лют стор. 2.png
    - assets/pictures/15_02-21_02/Газета 15-21 лют стор. 3.png
    - assets/pictures/15_02-21_02/Газета 15-21 лют стор. 4.png
    - assets/pictures/15_02-21_02/Газета 15-21 лют стор. 5.png
    - assets/pictures/15_02-21_02/Газета 15-21 лют стор. 6.png
    - assets/sounds/puk-v-ekho.wav
    - assets/pictures/hy.jpg

  fonts:
    - family: Minecraft
      fonts:
        - asset: assets/fonts/Minecraft_1.1.ttf
